# League of Legends Music Analysis

## Data Manipulation for Music data

### Import Library

In [1]:
import pandas as pd
import numpy as np
import statistics as st
import matplotlib as ml

### Import Music Data

In [2]:
music = pd.read_csv("League of Legends Music List_20230920 - List of Music.csv")
music.head()

,track_id,track_title,artist,artist_2,genre,album_detail,album_title,release_year,youtube_year,duration,duration_second,release_for,release_for_detail,note,spotify_stream,youtube_views
0,1,Thornmail,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:44,224,Project Group,Pentakill,NaN,9279043.0,4701409.0
1,2,Last Whisper,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:38,218,Project Group,Pentakill,NaN,12483786.0,8052780.0
2,3,Ohmwrecker,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,05:18,318,Project Group,Pentakill,NaN,6983121.0,4052630.0
3,4,The Prophecy,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,00:47,47,Project Group,Pentakill,NaN,2600172.0,1306477.0
4,5,Lightbringer,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,04:56,296,Project Group,Pentakill,NaN,39998999.0,37164361.0

### Clean Null Rows

In [3]:
music.dropna(subset = "track_id", inplace = True)

### Check Data Types

In [4]:
music.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 716 entries, 0 to 715
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            716 non-null    int64
 1   track_title         716 non-null    object
 2   artist              715 non-null    object
 3   artist_2            317 non-null    object
 4   genre               716 non-null    object
 5   album_detail        716 non-null    object
 6   album_title         716 non-null    object
 7   release_year        716 non-null    int64
 8   youtube_year        174 non-null    float64
 9   duration            716 non-null    object
 10  duration_second     716 non-null    int64
 11  release_for         708 non-null    object
 12  release_for_detail  640 non-null    object
 13  note                10 non-null     object
 14  spotify_stream      709 non-null    float64
 15  youtube_views       310 non-null    float64
dtypes: float64(3), int64(3), object(10)
memory usage: 89.6+ KB

### Set track_id as index

In [5]:
music = music.set_index("track_id")
music

,track_title,artist,artist_2,genre,album_detail,album_title,release_year,youtube_year,duration,duration_second,release_for,release_for_detail,note,spotify_stream,youtube_views
track_id,,,,,,,,,,,,,,,
1,Thornmail,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:44,224,Project Group,Pentakill,NaN,9279043.0,4701409.0
2,Last Whisper,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:38,218,Project Group,Pentakill,NaN,12483786.0,8052780.0
3,Ohmwrecker,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,05:18,318,Project Group,Pentakill,NaN,6983121.0,4052630.0
4,The Prophecy,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,00:47,47,Project Group,Pentakill,NaN,2600172.0,1306477.0
5,Lightbringer,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,04:56,296,Project Group,Pentakill,NaN,39998999.0,37164361.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,My Honeyfruit! (Launch Cinematic),League of Legends,NaN,Soundtrack,Album,Runeterra Reforged (Original Soundtrack),2023,NaN,01:52,112,Related Game,Teamfight Tactics,NaN,52109.0,NaN
713,Preparation,League of Legends,NaN,Soundtrack,Album,Runeterra Reforged (Original Soundtrack),2023,NaN,02:01,121,Related Game,Teamfight Tactics,NaN,38272.0,NaN
714,Fragments from Runeterra (Pt. 1),League of Legends,NaN,Soundtrack,Album,Runeterra Reforged (Original Soundtrack),2023,NaN,04:45,285,Related Game,Teamfight Tactics,NaN,34361.0,NaN
715,Teamfight Tactics — Runeterra Reforged,League of Legends,NaN,Soundtrack,Album,Runeterra Reforged (Original Soundtrack),2023,NaN,05:10,310,Related Game,Teamfight Tactics,NaN,97057.0,NaN
716,Shrine of the First Lands — Triumph,League of Legends,NaN,Soundtrack,Album,Runeterra Reforged (Original Soundtrack),2023,NaN,02:30,150,Related Game,Teamfight Tactics,NaN,37459.0,NaN

### Clean Data Types of Other Columns

In [6]:
music["spotify_stream"] = music["spotify_stream"].fillna(0)
music["spotify_stream"] = music["spotify_stream"].astype(int)

In [7]:
music["youtube_views"] = music["youtube_views"].fillna(0)
music["youtube_views"] = music["youtube_views"].astype(int)

In [8]:
music["release_for"] = music["release_for"].astype(str)

In [9]:
music.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 716 entries, 1 to 716
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_title         716 non-null    object
 1   artist              715 non-null    object
 2   artist_2            317 non-null    object
 3   genre               716 non-null    object
 4   album_detail        716 non-null    object
 5   album_title         716 non-null    object
 6   release_year        716 non-null    int64
 7   youtube_year        174 non-null    float64
 8   duration            716 non-null    object
 9   duration_second     716 non-null    int64
 10  release_for         716 non-null    object
 11  release_for_detail  640 non-null    object
 12  note                10 non-null     object
 13  spotify_stream      716 non-null    int64
 14  youtube_views       716 non-null    int64
dtypes: float64(1), int64(4), object(10)
memory usage: 89.5+ KB

### Clean release_for and release_for_detail

In [10]:
release_for_null = music[music["release_for"].isnull()]
release_for_null.index

Int64Index([], dtype='int64', name='track_id')

In [11]:
music.loc[[532, 533, 534, 535, 536, 537, 538, 539], "release_for"] = "Original Story"

In [12]:
music.loc[539]

track_title                                        What Could Have Been
artist                                                            Sting
artist_2                                                       Ray Chen
genre                                                       Alternative
album_detail                                                     Single
album_title           What Could Have Been (From the series Arcane L...
release_year                                                       2021
youtube_year                                                        NaN
duration                                                          03:33
duration_second                                                     213
release_for                                              Original Story
release_for_detail                                                  NaN
note                                                                NaN
spotify_stream                                                 50651400
youtube_views                                                  14043080
Name: 539, dtype: object

In [13]:
music.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 716 entries, 1 to 716
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_title         716 non-null    object
 1   artist              715 non-null    object
 2   artist_2            317 non-null    object
 3   genre               716 non-null    object
 4   album_detail        716 non-null    object
 5   album_title         716 non-null    object
 6   release_year        716 non-null    int64
 7   youtube_year        174 non-null    float64
 8   duration            716 non-null    object
 9   duration_second     716 non-null    int64
 10  release_for         716 non-null    object
 11  release_for_detail  640 non-null    object
 12  note                10 non-null     object
 13  spotify_stream      716 non-null    int64
 14  youtube_views       716 non-null    int64
dtypes: float64(1), int64(4), object(10)
memory usage: 105.7+ KB

In [14]:
music.loc[[532, 533, 534, 535, 536, 537, 538, 539], "release_for_detail"] = "Arcane League of Legends"

In [15]:
music.loc[539]

track_title                                        What Could Have Been
artist                                                            Sting
artist_2                                                       Ray Chen
genre                                                       Alternative
album_detail                                                     Single
album_title           What Could Have Been (From the series Arcane L...
release_year                                                       2021
youtube_year                                                        NaN
duration                                                          03:33
duration_second                                                     213
release_for                                              Original Story
release_for_detail                             Arcane League of Legends
note                                                                NaN
spotify_stream                                                 50651400
youtube_views                                                  14043080
Name: 539, dtype: object

### Create New Category using release_for

In [16]:
release_for_uniq = pd.DataFrame(music["release_for"].unique())
release_for_uniq

                           0
0              Project Group
1              Esports Event
2         Skin Theme Release
3   Original Game Soundtrack
4              In-game Event
5                      Remix
6                  Cinematic
7           Champion Release
8            Champion Rework
9             Original Story
10              Related Game
11             Collaboration

In [17]:
music.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 716 entries, 1 to 716
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_title         716 non-null    object
 1   artist              715 non-null    object
 2   artist_2            317 non-null    object
 3   genre               716 non-null    object
 4   album_detail        716 non-null    object
 5   album_title         716 non-null    object
 6   release_year        716 non-null    int64
 7   youtube_year        174 non-null    float64
 8   duration            716 non-null    object
 9   duration_second     716 non-null    int64
 10  release_for         716 non-null    object
 11  release_for_detail  648 non-null    object
 12  note                10 non-null     object
 13  spotify_stream      716 non-null    int64
 14  youtube_views       716 non-null    int64
dtypes: float64(1), int64(4), object(10)
memory usage: 105.7+ KB

In [18]:
def set_category(row):
    
    release_for = row[10]
    
    if release_for == "Champion Release":
        return "Original Game"
    if release_for == "Champion Rework":
        return "Original Game"
    if release_for == "In-game Event":
        return "Original Game"
    if release_for == "Original Game Soundtrack":
        return "Original Game"
    if release_for == "Skin Theme Release":
        return "Original Game"
    if release_for == "Project Group":
        return "IP Variation"
    if release_for == "Remix":
        return "IP Variation"
    if release_for == "Cinematic":
        return "IP Variation"
    if release_for == "Original Story":
        return "IP Variation"
    if release_for == "Related Game":
        return "IP Variation"
    if release_for == "Collaboration":
        return "IP Variation"
    if release_for == "Esports Event":
        return "E-Sports"
    else:
        return "needed to be specified"
    
music["category"] = music.apply(set_category, axis = "columns")

In [19]:
music.head(20)

,track_title,artist,artist_2,genre,album_detail,album_title,release_year,youtube_year,duration,duration_second,release_for,release_for_detail,note,spotify_stream,youtube_views,category
track_id,,,,,,,,,,,,,,,,
1,Thornmail,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:44,224,Project Group,Pentakill,NaN,9279043,4701409,IP Variation
2,Last Whisper,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:38,218,Project Group,Pentakill,NaN,12483786,8052780,IP Variation
3,Ohmwrecker,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,05:18,318,Project Group,Pentakill,NaN,6983121,4052630,IP Variation
4,The Prophecy,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,00:47,47,Project Group,Pentakill,NaN,2600172,1306477,IP Variation
5,Lightbringer,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,04:56,296,Project Group,Pentakill,NaN,39998999,37164361,IP Variation
6,Orb of Winter,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,03:32,212,Project Group,Pentakill,NaN,4437258,2871844,IP Variation
7,Deathfire Grasp,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,04:00,240,Project Group,Pentakill,NaN,21959507,20009298,IP Variation
8,The Hex Core,Pentakill,NaN,Metal,Album,Smite and Ignite,2014,NaN,04:34,274,Project Group,Pentakill,NaN,4201203,2168331,IP Variation
9,Warriors,Imagine Dragons,NaN,Alternative,Single,Warriors - Single,2014,NaN,02:50,170,Esports Event,2014 World Championship,NaN,632826969,409766905,E-Sports
10,Bit Rush,League of Legends,NaN,Dance,Single,Bit Rush - Single,2015,NaN,02:31,151,Skin Theme Release,Arcade,NaN,5497259,4347959,Original Game
11,Demacia Rising,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,04:08,248,Original Game Soundtrack,NaN,NaN,6715523,5801737,Original Game
12,Daylight's End,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,03:46,226,Original Game Soundtrack,NaN,NaN,2299428,1967345,Original Game
13,Freljord,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,03:31,211,Original Game Soundtrack,NaN,NaN,2375537,2598353,Original Game
14,Super Galaxy Rumble,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,01:59,119,Original Game Soundtrack,NaN,NaN,1803928,1001180,Original Game
15,Get Jinxed,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,02:35,155,Original Game Soundtrack,NaN,NaN,90106580,125482377,Original Game
16,Reborn,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,02:44,164,Original Game Soundtrack,NaN,NaN,1297932,884211,Original Game
17,Tales of the Rift,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,03:35,215,Original Game Soundtrack,NaN,NaN,2227006,1851961,Original Game
18,Tidecaller,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,04:14,254,Original Game Soundtrack,NaN,NaN,4134711,3572999,Original Game
19,Braum,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,03:34,214,Original Game Soundtrack,NaN,NaN,6377486,4943627,Original Game
20,Quinn and Valor,League of Legends,NaN,Soundtrack,Album,The Music of League of Legends Volume 1,2015,NaN,03:30,210,Original Game Soundtrack,NaN,NaN,2432420,2404241,Original Game

In [20]:
music["category"].astype("category")

track_id
1      IP Variation
2      IP Variation
3      IP Variation
4      IP Variation
5      IP Variation
           ...
712    IP Variation
713    IP Variation
714    IP Variation
715    IP Variation
716    IP Variation
Name: category, Length: 716, dtype: category
Categories (3, object): ['E-Sports', 'IP Variation', 'Original Game']

### Split DataFrame into music_info and music_stream_stat

In [21]:
music_info = music[["track_title", "artist", "artist_2", "genre", "album_title", "release_year", "duration", "duration_second","category", "release_for", "release_for_detail"]]
music_info

,track_title,artist,artist_2,genre,album_title,release_year,duration,duration_second,category,release_for,release_for_detail
track_id,,,,,,,,,,,
1,Thornmail,Pentakill,NaN,Metal,Smite and Ignite,2014,03:44,224,IP Variation,Project Group,Pentakill
2,Last Whisper,Pentakill,NaN,Metal,Smite and Ignite,2014,03:38,218,IP Variation,Project Group,Pentakill
3,Ohmwrecker,Pentakill,NaN,Metal,Smite and Ignite,2014,05:18,318,IP Variation,Project Group,Pentakill
4,The Prophecy,Pentakill,NaN,Metal,Smite and Ignite,2014,00:47,47,IP Variation,Project Group,Pentakill
5,Lightbringer,Pentakill,NaN,Metal,Smite and Ignite,2014,04:56,296,IP Variation,Project Group,Pentakill
...,...,...,...,...,...,...,...,...,...,...,...
712,My Honeyfruit! (Launch Cinematic),League of Legends,NaN,Soundtrack,Runeterra Reforged (Original Soundtrack),2023,01:52,112,IP Variation,Related Game,Teamfight Tactics
713,Preparation,League of Legends,NaN,Soundtrack,Runeterra Reforged (Original Soundtrack),2023,02:01,121,IP Variation,Related Game,Teamfight Tactics
714,Fragments from Runeterra (Pt. 1),League of Legends,NaN,Soundtrack,Runeterra Reforged (Original Soundtrack),2023,04:45,285,IP Variation,Related Game,Teamfight Tactics
715,Teamfight Tactics — Runeterra Reforged,League of Legends,NaN,Soundtrack,Runeterra Reforged (Original Soundtrack),2023,05:10,310,IP Variation,Related Game,Teamfight Tactics
716,Shrine of the First Lands — Triumph,League of Legends,NaN,Soundtrack,Runeterra Reforged (Original Soundtrack),2023,02:30,150,IP Variation,Related Game,Teamfight Tactics

In [22]:
music_info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 716 entries, 1 to 716
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_title         716 non-null    object
 1   artist              715 non-null    object
 2   artist_2            317 non-null    object
 3   genre               716 non-null    object
 4   album_title         716 non-null    object
 5   release_year        716 non-null    int64
 6   duration            716 non-null    object
 7   duration_second     716 non-null    int64
 8   category            716 non-null    object
 9   release_for         716 non-null    object
 10  release_for_detail  648 non-null    object
dtypes: int64(2), object(9)
memory usage: 83.3+ KB

In [23]:
music_stream_stat = music[["track_title", "release_year", "youtube_year","duration_second", "spotify_stream", "youtube_views"]]
music_stream_stat

,track_title,release_year,youtube_year,duration_second,spotify_stream,youtube_views
track_id,,,,,,
1,Thornmail,2014,NaN,224,9279043,4701409
2,Last Whisper,2014,NaN,218,12483786,8052780
3,Ohmwrecker,2014,NaN,318,6983121,4052630
4,The Prophecy,2014,NaN,47,2600172,1306477
5,Lightbringer,2014,NaN,296,39998999,37164361
...,...,...,...,...,...,...
712,My Honeyfruit! (Launch Cinematic),2023,NaN,112,52109,0
713,Preparation,2023,NaN,121,38272,0
714,Fragments from Runeterra (Pt. 1),2023,NaN,285,34361,0
715,Teamfight Tactics — Runeterra Reforged,2023,NaN,310,97057,0
716,Shrine of the First Lands — Triumph,2023,NaN,150,37459,0

In [24]:
music_stream_stat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 716 entries, 1 to 716
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   track_title      716 non-null    object
 1   release_year     716 non-null    int64
 2   youtube_year     174 non-null    float64
 3   duration_second  716 non-null    int64
 4   spotify_stream   716 non-null    int64
 5   youtube_views    716 non-null    int64
dtypes: float64(1), int64(4), object(1)
memory usage: 55.3+ KB

### Import Album info data

In [25]:
album_info = pd.read_csv("League of Legends Music List_20230920 - Album Info.csv")
album_info.head()

,album_id,album_detail,album_title,release_year
0,1,Album,Smite and Ignite,2014
1,2,Single,Warriors - Single,2014
2,3,Single,Bit Rush - Single,2015
3,4,Album,The Music of League of Legends Volume 1,2015
4,5,Single,Welcome to Planet Urf - Single,2015

In [26]:
album_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      123 non-null    int64
 1   album_detail  123 non-null    object
 2   album_title   123 non-null    object
 3   release_year  123 non-null    int64
dtypes: int64(2), object(2)
memory usage: 4.0+ KB

In [27]:
album_info["album_detail"].astype("category")

0       Album
1      Single
2      Single
3       Album
4      Single
        ...
118    Single
119    Single
120        EP
121    Single
122     Album
Name: album_detail, Length: 123, dtype: category
Categories (3, object): ['Album', 'EP', 'Single']

### Set album_id as index

In [28]:
album_info = album_info.set_index("album_id")
album_info

,album_detail,album_title,release_year
album_id,,,
1,Album,Smite and Ignite,2014
2,Single,Warriors - Single,2014
3,Single,Bit Rush - Single,2015
4,Album,The Music of League of Legends Volume 1,2015
5,Single,Welcome to Planet Urf - Single,2015
...,...,...,...
119,Single,Orgulho Loco (feat. League of Legends Brasil &...,2023
120,Single,Rules (Are Meant to Break) - Single,2023
121,EP,Soul Fighter (Original Soundtrack) - EP,2023
122,Single,Space and Time (feat. League of Legends) - Single,2023
123,Album,The Mageseeker: A League of Legends Story ((Of...,2023

### Export DataFrames as CSV files

In [29]:
music_info.to_csv("music_info.csv")

In [30]:
album_info.to_csv("album_info.csv")

In [31]:
music_stream_stat.to_json("music_stream_stat.csv")

## Connect MySQL Server with Python

In [32]:
import sqlalchemy
username = 'root'
password = '****blindpassword****'
host = 'localhost'
database= 'lolmusic'
db_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.
                                               format(username, password, 
                                                      host, database))

### Export DataFrames to MySQL Server

In [33]:
music_info.to_sql(con=db_connection, name='music_info', if_exists='replace')

716

In [34]:
album_info.to_sql(con=db_connection, name='album_info', if_exists='replace')

123

In [35]:
music_stream_stat.to_sql(con=db_connection, name='music_stream_stat', if_exists='replace')

716

## Data Manipulation of Game data

### Import Game related data

In [36]:
game_stat = pd.read_csv("League of Legends Music List_20230920 - Game Stats.csv")
game_stat.index.name='season_id'
game_stat.head()

,year,season,total_user,monthly_active_user,daily_active_user,revenue
season_id,,,,,,
0,2022,12,NaN,151609154,5069411.0,1.80
1,2021,11,NaN,149312721,4977091.0,1.63
2,2020,10,NaN,136744216,4558140.0,1.75
3,2019,9,NaN,116655965,3888532.0,1.50
4,2018,8,NaN,75000000,NaN,1.40

In [37]:
game_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 12 non-null     int64
 1   season               12 non-null     int64
 2   total_user           2 non-null      float64
 3   monthly_active_user  12 non-null     int64
 4   daily_active_user    4 non-null      float64
 5   revenue              8 non-null      float64
dtypes: float64(3), int64(3)
memory usage: 708.0 bytes

In [38]:
game_advanced = pd.read_csv("League of Legends Music List_20230920 - Game Advanced.csv")
game_advanced.index.name='update_id'
game_advanced.head()

           year   update_category update_detail      update_fullname
update_id
0          2009  Champion Release       Alistar         the Minotaur
1          2009  Champion Release         Annie       the Dark Child
2          2009  Champion Release          Ashe     the Frost Archer
3          2009  Champion Release  Fiddlesticks     the Ancient Fear
4          2009  Champion Release           Jax  Grandmaster at Arms

In [39]:
game_advanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             218 non-null    int64
 1   update_category  218 non-null    object
 2   update_detail    218 non-null    object
 3   update_fullname  165 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.9+ KB

In [40]:
other_games = pd.read_csv("League of Legends Music List_20230920 - Other Game Stats_2023.csv")
other_games.index.name='games_id'
other_games.head()

                       game  monthly_active_players release_date
games_id
0                      PUBG               376000000   2017-03-23
1                  Fortnite               263000000   2017-07-21
2                    Roblox               205000000   2006-09-01
3                 Minecraft               171000000   2011-11-18
4         League of Legends               152000000   2009-10-27

In [41]:
other_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game                    10 non-null     object
 1   monthly_active_players  10 non-null     int64
 2   release_date            10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [42]:
other_games["release_date"] = other_games["release_date"].astype("datetime64")

In [43]:
player_demographic = pd.read_csv("League of Legends Music List_20230920 - Player Demographic_2023.csv")
player_demographic.index.name='feature_id'
player_demographic.head()

             category category_detail value
feature_id
0              Gender            Male   87%
1              Gender          Female   12%
2              Gender      Non-Binary    1%
3           Age Group        Under 18   10%
4           Age Group           18-20   27%

In [44]:
player_demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   category         23 non-null     object
 1   category_detail  23 non-null     object
 2   value            23 non-null     object
dtypes: object(3)
memory usage: 684.0+ bytes

### Export DataFrames to SQL Server

In [45]:
game_stat.to_sql(con=db_connection, name='game_stat', if_exists='replace')

12

In [46]:
game_advanced.to_sql(con=db_connection, name='game_advanced', if_exists='replace')

218

In [47]:
other_games.to_sql(con=db_connection, name='other_games', if_exists='replace')

10

In [48]:
player_demographic.to_sql(con=db_connection, name='player_demographic', if_exists='replace')

23

## Data Manipulation of Esports data

### Import Esports related data

In [49]:
esports_events = pd.read_csv("League of Legends Music List_20230920 - Esports Events.csv")
esports_events = esports_events.set_index("event_id")
esports_events.head()

,year,category,event_name,event_location,peak_concurrent_viewership,peak_viewership,avg_viewership,hours_watched
event_id,,,,,,,,
1,2011,World Championship,2011 World Championship,Jönköping,210069.0,NaN,NaN,NaN
2,2012,World Championship,2012 World Championship,Los Angeles,1100000.0,NaN,NaN,NaN
3,2013,World Championship,2013 World Championship,Los Angeles,8500000.0,NaN,NaN,NaN
4,2013,All-Star Event,2013 League of Legends All-Star Event,Sanghai,NaN,NaN,NaN,NaN
5,2015,Mid - Season Invitational,2015 Mid - Season Invitational,Tallahassee,NaN,NaN,NaN,NaN

In [50]:
esports_events.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 1 to 33
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   year                        33 non-null     int64
 1   category                    33 non-null     object
 2   event_name                  33 non-null     object
 3   event_location              33 non-null     object
 4   peak_concurrent_viewership  11 non-null     float64
 5   peak_viewership             23 non-null     float64
 6   avg_viewership              23 non-null     float64
 7   hours_watched               23 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 2.3+ KB

### Export DataFrames to SQL Server

In [51]:
esports_events.to_sql(con=db_connection, name='esports_events', if_exists='replace')

33